export const ELEMENTS = {
    titulo : 'Impressão do Contrato',
    botaoContrato : '#printContratoViaProponente',
    classeModal : '[class="fancybox-skin"]',
    idPreBenef : '#idPreBeneficiario',
    subselector : 'div',
    subclasseSelector : 'fancybox-item fancybox-close',
    xpathNomeSocial : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[2]/span',
    xpathNomeBenef : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[3]/span',
    xpathNomeMae: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[4]/span',
    xpathDataNasc: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[5]/span',
    xpathRG: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[6]/span',
    xpathCPF: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[7]/span',
    xpathEmail: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[8]/span',
    xpathCelular: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[10]/span',
    xpathAdesao: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[12]/span',
    xpathMensal : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[14]/span',
    botaoAvancar : '#avancar',
    mensagemErro : '.noty_text',
    mensagemErroContrato : 'É necessário imprimir o contrato para avançar!',
    mensagemErroBotaoFechar : '.noty_exit',
    xpathNomeBenefSemNomeSocial : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[2]/span',
    xpathNomeMaeSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[3]/span',
    xpathDataNascSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[4]/span',
    xpathRGSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[5]/span',
    xpathCPFSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[6]/span',
    xpathEmailSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[7]/span',
    xpathCelularSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[9]/span',
    xpathAdesaoSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[11]/span',
    xpathMensalSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[13]/span',
}