
export const ELEMENTS = {
    titulo : 'Dados do Beneficiário',
    nome : '[name="preBeneficiario.nome"]',
    nomeSocial : '[name="preBeneficiario.nomeSocial"]',
    generoSocial : '[name="preBeneficiario.idGeneroSocial"]',
    estadoCivil : '[name="preBeneficiario.estadoCivilE.id"]',
    estadoCivilText : 'Solteiro(a)',
    nomeMae : '[name="preBeneficiario.nomeMae"]',
    rg : '[name="preBeneficiario.rg"]',
    rgValue : '450453224',
    cpf : '[name="preBeneficiario.cpf"]',
    cns: '[name="preBeneficiario.cns"]',
    sexo : '[name="preBeneficiario.sexo"]',
    dataNascimento : '[name="preBeneficiario.dataNascimento"]',
    orgaoEmissor : '[name="preBeneficiario.orgaoEmissor"]',
    orgaoEmissorValue : 'SSP',
    orgaoEmissorText : 'Secretaria de Segurança Pública-SSP',
    elementoProfissao : '[name="preBeneficiario.profissao"]',
    classeProfissao : '[class="atualizar-profissao"]',
    subElementoProfissao : 'div',
    classeDivSubElemento : 'selectize-control obrigatorio default tags-select single',
    profissao : "ACESSOR {enter}",
    ufOrgaoEmissor : '[name="preBeneficiario.ufOrgaoEmissor"]',
    ufOrgaoEmissorValueText : 'SP',
    email : '[name="preBeneficiario.email"]',
    cep : '[name="preBeneficiario.endereco.cep"]',
    cepCorrespondencia : '#correspondencia-cep',
    cuidadoAnteriorText : 'Particular',
    cuidadoAnteriorValue : 'PARTICULAR',
    logradouro : '[name="preBeneficiario.endereco.logradouro"]',
    numeroEnd : '[name="preBeneficiario.endereco.numero"]',
    checkboxEnd : "#trasf-endereco",
    cuidadoAnterior : '[name="preBeneficiario.tipoCuidadoAnterior"]',
    radioDebitoAuomaticoSim : '#radioDebitoAutomaticoSim',
    debAutomDadosBenefCheckbox : '#utilizar-dados-do-beneficiario',
    banco : '#banco_debito_automatico',
    agencia : '#agencia_debito_automatico',
    cc : '#conta_debito_automatico',
    dtNasc : Cypress.env('dtNasc'),
    bancoText : 'ITAÚ UNIBANCO S.A.',
    botaoAvancar : '#saveAndNext',
    avisoDebitoAutomatico : '[class="aviso aviso-atencao"]',
    checkboxDocumentos : '#documentos',
    janelaDeAviso : '#noty_bottomFooter_layout_container',
    
}