
export const ELEMENTS = {
    titulo : 'Dados do Beneficiário',
    nome : '[name="preBeneficiario.nome"]',
    nomeSocial : '[name="preBeneficiario.nomeSocial"]',
    generoSocial : '[name="preBeneficiario.idGeneroSocial"]',
    estadoCivil : '[name="preBeneficiario.estadoCivilE.id"]',
    nomeMae : '[name="preBeneficiario.nomeMae"]',
    rg : '[name="preBeneficiario.rg"]',
    cpf : '[name="preBeneficiario.cpf"]',
    cns: '[name="preBeneficiario.cns"]',
    sexo : '[name="preBeneficiario.sexo"]',
    dataNascimento : '[name="preBeneficiario.dataNascimento"]',
    orgaoEmissor : '[name="preBeneficiario.orgaoEmissor"]',
    elementoProfissao : '[name="preBeneficiario.profissao"]',
    classeProfissao : '[class="atualizar-profissao"]',
    subElementoProfissao : 'div',
    classeDivSubElemento : 'selectize-control obrigatorio default tags-select single',
    profissao : "ACESSOR {enter}",
    ufOrgaoEmissor : '[name="preBeneficiario.ufOrgaoEmissor"]',
    email : '[name="preBeneficiario.email"]',
    cep : '[name="preBeneficiario.endereco.cep"]',
    tipoLogradouro : '[name="preBeneficiario.endereco.tipoLogradouro"]',
    logradouro : '#proponente-logradouro',
    numeroEnd : '[name="preBeneficiario.endereco.numero"]',
    complemento : '[name="preBeneficiario.endereco.complemento"]',
    bairro : '[name="preBeneficiario.endereco.bairro"]',
    cidade : '[name="preBeneficiario.endereco.cidade"]',
    UF : '[name="preBeneficiario.endereco.uf"]',
    ibge : '[name="preBeneficiario.endereco.codCidade"]',
    cepCorrespondencia : '#correspondencia-cep',
    tipoLogradouroCorrespondencia : '[name="preBeneficiario.endereco.tipoLogradouro"]',
    logradouroCorrespondencia : '[name="preBeneficiario.endereco.logradouro"]',
    numeroEndCorrespondencia : '[name="preBeneficiario.endereco.numero"]',
    complementoCorrespondencia: '[name="preBeneficiario.endereco.complemento"]',
    bairroCorrespondencia : '[name="preBeneficiario.endereco.bairro"]',
    cidadeCorrespondencia : '[name="preBeneficiario.endereco.cidade"]',
    UFCorrespondencia : '[name="preBeneficiario.endereco.uf"]',
    ibgeCorrespondencia : '[name="preBeneficiario.endereco.codCidade"]',
    cuidadoAnteriorText : 'Particular',
    cuidadoAnteriorValue : 'PARTICULAR',
    checkboxEnd : "#trasf-endereco",
    cuidadoAnterior : '[name="preBeneficiario.tipoCuidadoAnterior"]',
    radioDebitoAuomaticoSim : '#radioDebitoAutomaticoSim',
    debAutomDadosBenefCheckbox : '#utilizar-dados-do-beneficiario',
    banco : '#banco_debito_automatico',
    agencia : '#agencia_debito_automatico',
    cc : '#conta_debito_automatico',
    botaoAvancar : '#saveAndNext',
    avisoDebitoAutomatico : '[class="aviso aviso-atencao"]',
    checkboxDocumentos : '#documentos',
    mensagemErroDocumentos : '-Por favor selecione a opção de anexar documentos.',
    botaoFecharJanelErro : '.noty_exit',
    janelaDeAviso : '.noty_text',
    numeroCel : '[name="preBeneficiario.telefoneCelular.numero"]',
}