export const ELEMENTS = {
    titulo : 'Conferência de informações',
    parceriaVenda : '#parceriaVenda',
    assinaturaDigital : '#selectAssinaturaDigital',
    pagamentoAdesao : '#selectFormaPagamento',
    pagamentoMensalidade : '[name="preBeneficiario.formaPagamentoMensalidade"]',
    botaoAvancar : "#save",
    nome : '[name="preBeneficiario.nome"]',
    nomeSocial : '[name="preBeneficiario.nomeSocial"]',
    generoSocial : '[name="preBeneficiario.idGeneroSocial"]',
    estadoCivil : '[name="preBeneficiario.estadoCivilE.id"]',
    telCelular : '[name="preBeneficiario.telefoneCelular.numero"]',
    nomeMae : '[name="preBeneficiario.nomeMae"]',
    rg : '[name="preBeneficiario.rg"]',
    rgValue : '450453224',
    cpf : '[name="preBeneficiario.cpf"]',
    cns: '[name="preBeneficiario.cns"]',
    sexo : '[name="preBeneficiario.sexo"]',
    dataNascimento : '[name="preBeneficiario.dataNascimento"]',
    orgaoEmissor : '[name="preBeneficiario.orgaoEmissor"]',
    orgaoEmissorValue : 'SSP',
    orgaoEmissorText : 'Secretaria de Segurança Pública-SSP',
    elementoProfissao : '[name="preBeneficiario.profissao"]',
    classeProfissao : '[class="atualizar-profissao"]',
    subElementoProfissao : 'div',
    classeDivSubElemento : 'selectize-control obrigatorio default tags-select single',
    profissao : "ACESSOR {enter}",
    ufOrgaoEmissor : '[name="preBeneficiario.ufOrgaoEmissor"]',
    ufOrgaoEmissorValueText : 'SP',
    email : '[name="preBeneficiario.email"]',
    cep : '[name="preBeneficiario.endereco.cep"]',
    cepCorrespondencia : '#correspondencia-cep',
    cuidadoAnteriorText : 'Particular',
    cuidadoAnteriorValue : 'PARTICULAR',
    logradouro : '[name="preBeneficiario.endereco.logradouro"]',
    numeroEnd : '[name="preBeneficiario.endereco.numero"]',
    checkboxEnd : "#trasf-endereco",
    cuidadoAnterior : '[name="preBeneficiario.tipoCuidadoAnterior"]',
    justificativa3 : '#text-2893',
    bancoDebito : '341 - ITAÚ UNIBANCO S.A.',
    xpathNomeDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[1]/label[2]',
    xpathCPFDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[2]/label[2]',
    xpathBancoDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[3]/label[2]',
    xpathAgenciaDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[4]/label[2]',
    xpathContaCDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[5]/label[2]'
}