export const ELEMENTS = {
    titulo : 'Conferência de informações',
    tituloCorretora : 'Conferência Corretor Credenciado',
    comoConheceu : '#comoConheceu',
    opcaoConheceu : 'Shopping Pátio Paulista',
    parceriaVenda : '#parceriaVenda',
    assinaturaDigital : '#selectAssinaturaDigital',
    pagamentoAdesao : '#selectFormaPagamento',
    pagamentoMensalidade : '[name="preBeneficiario.formaPagamentoMensalidade"]',
    botaoAvancar : "#save",
    nome : '[name="preBeneficiario.nome"]',
    nomeSocial : '[name="preBeneficiario.nomeSocial"]',
    generoSocial : '[name="preBeneficiario.idGeneroSocial"]',
    estadoCivil : '[name="preBeneficiario.estadoCivilE.id"]',
    telCelular : '[name="preBeneficiario.telefoneCelular.numero"]',
    nomeMae : '[name="preBeneficiario.nomeMae"]',
    rg : '[name="preBeneficiario.rg"]',
    cpf : '[name="preBeneficiario.cpf"]',
    cns: '[name="preBeneficiario.cns"]',
    sexo : '[name="preBeneficiario.sexo"]',
    dataNascimento : '[name="preBeneficiario.dataNascimento"]',
    orgaoEmissor : '[name="preBeneficiario.orgaoEmissor"]',
    elementoProfissao : '[name="preBeneficiario.profissao"]',
    classeProfissao : '[class="atualizar-profissao"]',
    subElementoProfissao : 'div',
    classeDivSubElemento : 'selectize-control obrigatorio default tags-select single',
    profissao : "ACESSOR",
    profissaoCampo : '#profissao-tag',
    ufOrgaoEmissor : '[name="preBeneficiario.ufOrgaoEmissor"]',
    email : '[name="preBeneficiario.email"]',
    cep : '[name="preBeneficiario.endereco.cep"]',
    tipoLogradouro : '[name="preBeneficiario.endereco.tipoLogradouro"]',
    logradouro : '[name="preBeneficiario.endereco.logradouro"]',
    numeroEnd : '[name="preBeneficiario.endereco.numero"]',
    complemento : '[name="preBeneficiario.endereco.complemento"]',
    bairro : '[name="preBeneficiario.endereco.bairro"]',
    cidade : '[name="preBeneficiario.endereco.cidade"]',
    UF : '[name="preBeneficiario.endereco.uf"]',
    ibge : '[name="preBeneficiario.endereco.codCidade"]',
    cepCorrespondencia : '#correspondencia-cep',
    tipoLogradouroCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.tipoLogradouro"]',
    logradouroCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.logradouro"]',
    numeroEndCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.numero"]',
    complementoCorrespondencia: '[name="preBeneficiario.enderecoCorrespondencia.complemento"]',
    bairroCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.bairro"]',
    cidadeCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.cidade"]',
    UFCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.uf"]',
    ibgeCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.codCidade"]',
    cuidadoAnteriorText : 'Particular',
    cuidadoAnteriorValue : 'PARTICULAR',
    checkboxEnd : "#trasf-endereco",
    cuidadoAnterior : '[name="preBeneficiario.tipoCuidadoAnterior"]',
    justificativa1 : '#text-2891',
    justificativa2 : '#text-2892',
    justificativa3 : '#text-2893',
    justificativa4 : '#text-2894',
    justificativa5 : '#text-2895',
    justificativa6 : '#text-2896',
    justificativa7 : '#text-2897',
    justificativa8 : '#text-2898',
    justificativa9 : '#text-2899',
    justificativa10 : '#text-2900',
    justificativa11 : '#text-2901',
    justificativa12 : '#text-2902',
    justificativa13 : '#text-2903',
    justificativa14 : '#text-2904',
    justificativa15 : '#text-2905',
    xpathNomeDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[1]/label[2]',
    xpathCPFDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[2]/label[2]',
    xpathBancoDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[3]/label[2]',
    xpathAgenciaDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[4]/label[2]',
    xpathContaCDebAutom : '//*[@id="form"]/fieldset[7]/div/div/div[5]/label[2]',
    xpathNomeDebAutomCorretora : '//*[@id="form"]/fieldset[8]/div/div/div[1]/label[2]',
    xpathCPFDebAutomCorretora : '//*[@id="form"]/fieldset[8]/div/div/div[2]/label[2]',
    xpathBancoDebAutomCorretora : '//*[@id="form"]/fieldset[8]/div/div/div[3]/label[2]',
    xpathAgenciaDebAutomCorretora : '//*[@id="form"]/fieldset[8]/div/div/div[4]/label[2]',
    xpathContaCDebAutomCorretora : '//*[@id="form"]/fieldset[8]/div/div/div[5]/label[2]',
    contadorEndereco : '#counterEndProponente',
    contadorCorrespondencia : '#counterCorrespondencia',
    checkEnd : '#trasf-endereco',
}