export const ELEMENTS = {
    titulo : 'Envelope - Assinatura digital',
    botaoAssinaturaDigital : '#assinatura-digital',
    tituloPainel  :'Painel de vendas',
    elementoPainel : '[class="painel-name"]',
    botaoPrint : '#printBoleto',
    iframeBoleto : '[class="fancybox-iframe"]',
    elementoIframe : '[class="fancybox-skin"]',
    subElementoIframe : 'div',
    botaoFecharIframe : 'fancybox-item fancybox-close',
    xpathNomeSocial : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[2]/span',
    xpathNomeBenef : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[3]/span',
    xpathNomeMae: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[4]/span',
    xpathDataNasc: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[5]/span',
    xpathRG: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[6]/span',
    xpathCPF: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[7]/span',
    xpathEmail: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[8]/span',
    xpathCelular: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[10]/span',
    xpathAdesao: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[12]/span',
    xpathMensal : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[14]/span',
    xpathStatusAssinatura : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[15]/span',
    botaoAvancar : '#avancar',
    mensagemErro : '.noty_text',
    mensagemErroBotaoFechar : '.noty_exit',
    textoErroSemAssinatura : 'Não é possível avançar para impressão da carteirinha enquanto PreBeneficiario não assinar o contrato!',
    textoErroBoleto : 'É necessário gerar boleto para avançar!',
    xpathNomeBenefSemNomeSocial : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[2]/span',
    xpathNomeMaeSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[3]/span',
    xpathDataNascSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[4]/span',
    xpathRGSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[5]/span',
    xpathCPFSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[6]/span',
    xpathEmailSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[7]/span',
    xpathCelularSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[9]/span',
    xpathAdesaoSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[11]/span',
    xpathMensalSemNomeSocial: '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[13]/span',
    xpathStatusAssinaturaSemNomeSocial : '//*[@id="form"]/div[1]/section/div/div[2]/div/ul/li[14]/span',
}