export const ELEMENTS = {
    titulo : 'Revisão do beneficiário',
    parceriaVenda : '#parceriaVenda',
    assinaturaDigital : '#selectAssinaturaDigital',
    pagamentoAdesao : '#selectFormaPagamento',
    pagamentoMensalidade : '[name="preBeneficiario.formaPagamentoMensalidade"]',
    botaoAvancar : "#save",
    nome : '[name="preBeneficiario.nome"]',
    nomeSocial : '[name="preBeneficiario.nomeSocial"]',
    generoSocial : '[name="preBeneficiario.idGeneroSocial"]',
    estadoCivil : '[name="preBeneficiario.estadoCivilE.id"]',
    telCelular : '[name="preBeneficiario.telefoneCelular.numero"]',
    nomeMae : '[name="preBeneficiario.nomeMae"]',
    rg : '[name="preBeneficiario.rg"]',
    cpf : '[name="preBeneficiario.cpf"]',
    cns: '[name="preBeneficiario.cns"]',
    sexo : '[name="preBeneficiario.sexo"]',
    dataNascimento : '[name="preBeneficiario.dataNascimento"]',
    orgaoEmissor : '[name="preBeneficiario.orgaoEmissor"]',
    elementoProfissao : '[name="preBeneficiario.profissao"]',
    classeProfissao : '[class="atualizar-profissao"]',
    subElementoProfissao : 'div',
    classeDivSubElemento : 'selectize-control obrigatorio default tags-select single',
    profissao : "ACESSOR {enter}",
    ufOrgaoEmissor : '[name="preBeneficiario.ufOrgaoEmissor"]',
    email : '[name="preBeneficiario.email"]',
    cep : '[name="preBeneficiario.endereco.cep"]',
    tipoLogradouro : '[name="preBeneficiario.endereco.tipoLogradouro"]',
    logradouro : '[name="preBeneficiario.endereco.logradouro"]',
    numeroEnd : '[name="preBeneficiario.endereco.numero"]',
    complemento : '[name="preBeneficiario.endereco.complemento"]',
    bairro : '[name="preBeneficiario.endereco.bairro"]',
    cidade : '[name="preBeneficiario.endereco.cidade"]',
    UF : '[name="preBeneficiario.endereco.uf"]',
    ibge : '[name="preBeneficiario.endereco.codCidade"]',
    cepCorrespondencia : '#correspondencia-cep',
    tipoLogradouroCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.tipoLogradouro"]',
    logradouroCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.logradouro"]',
    numeroEndCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.numero"]',
    complementoCorrespondencia: '[name="preBeneficiario.enderecoCorrespondencia.complemento"]',
    bairroCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.bairro"]',
    cidadeCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.cidade"]',
    UFCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.uf"]',
    ibgeCorrespondencia : '[name="preBeneficiario.enderecoCorrespondencia.codCidade"]',
    cuidadoAnteriorText : 'Particular',
    cuidadoAnteriorValue : 'PARTICULAR',
    checkboxEnd : "#trasf-endereco",
    xpathCuidadoAnterior : '//*[@id="form"]/fieldset[5]/div/div/div[2]/label[2]',
    justificativa3 : '#row-2893 > td > .lbl-radio-info',
    xpathNomeDebAutom : '//*[@id="form"]/fieldset[14]/div/div/div[1]/label[2]',
    xpathCPFDebAutom : '//*[@id="form"]/fieldset[14]/div/div/div[2]/label[2]',
    xpathBancoDebAutom : '//*[@id="form"]/fieldset[14]/div/div/div[3]/label[2]',
    xpathAgenciaDebAutom : '//*[@id="form"]/fieldset[14]/div/div/div[4]/label[2]',
    xpathContaCDebAutom : '//*[@id="form"]/fieldset[14]/div/div/div[5]/label[2]'
}