export const ELEMENTS = {
    titulo : 'Pagamento',
    xpathNomeSocial : '//*[@id="form"]/div[1]/div[2]/div[2]/div/ul[2]/li[1]/span',
    xpathNomeBenef : '//*[@id="form"]/div[1]/div[2]/div[2]/div/ul[2]/li[2]/span',
    xpathAdesao: '//*[@id="form"]/div[1]/div[2]/div[2]/div/ul[2]/li[6]/span',
    xpathMensal : '//*[@id="form"]/div[1]/div[2]/div[2]/div/ul[2]/li[5]/span',
    xpathNomeDebAutom : '//*[@id="form"]/div[1]/section[2]/fieldset/div/div/div[1]/label[2]',
    xpathCPFDebAutom : '//*[@id="form"]/div[1]/section[2]/fieldset/div/div/div[2]/label[2]',
    xpathBancoDebAutom : '//*[@id="form"]/div[1]/section[2]/fieldset/div/div/div[3]/label[2]',
    xpathAgenciaDebAutom : '//*[@id="form"]/div[1]/section[2]/fieldset/div/div/div[4]/label[2]',
    xpathCCDebAutom : '//*[@id="form"]/div[1]/section[2]/fieldset/div/div/div[5]/label[2]',
    datNasc : '#valid-data',
    formaPgto : '#formaPagamentoSelect',
    botaoAvancar : '#avancar',
    elemPainel : '[class="painel-name"]',
    tituloPainel : 'Painel de vendas',
    mensagemSucesso : '.noty_text',
    mensagemSucessoTexto : 'Processo finalizado com sucesso.',
    xpathNomeBenefSemNomeSocial : '//*[@id="form"]/div[1]/div[2]/div[2]/div/ul[2]/li[1]/span',
    xpathAdesaoSemNomeSocial: '//*[@id="form"]/div[1]/div[2]/div[2]/div/ul[2]/li[5]/span',
    xpathMensalSemNomeSocial: '//*[@id="form"]/div[1]/div[2]/div[2]/div/ul[2]/li[4]/span',
}